config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#top'

  get 'home/about' => 'homes#index'  

  
   

  resources :users, only: [:show, :index, :new, :edit, :update] do
    member do
    get :following, :followers
    end
  end



  resources :books, only: [:index, :new, :create, :show, :edit, :destroy, :update] do
  	resource :favorites, only: [:create, :destroy] 
  	resource :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:index, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  validates :title, presence: true
  validates :body,
    presence: true,
    length: { maximum: 200 }
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  has_many :comments, dependent: :destroy
    
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
  	validates :following_id, presence: true
  	validates :follower_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy


  has_many :following, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following_user, through: :following, source: :follower
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follower_user, through: :follower, source: :following

  def follow(other_user)
    following.create(follower_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    following.find_by(follower_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following_user.include?(other_user)
  end

  attachment :profile_image
  validates :name,
    presence: true,
    length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  user_path(resource)
end

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!

  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @books = Book.new
    @comment = Comment.new
    @comments = current_user.comments.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comments = current_user.comments.new(comment_params)
    @comments.book_id = @book.id
    if @comments.save
      @url = request.referer
      redirect_to @url
    else
      @books = Book.new
      @comment = Comment.new
      render template: 'books/show'
    end

  end

  def destroy
    book = Book.find(params[:book_id])
    comment = current_user.comments.find_by(book_id: book.id)
    comment.destroy
    @url = request.referer
    redirect_to @url
  end

  private
  def comment_params
      params.require(:comment).permit(:comment)
  end
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    @url = request.referer
    redirect_to @url
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    @url = request.referer
    redirect_to @url
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:follower_id])
    current_user.follow(user)
    @url = request.referer
    redirect_to @url
  end

  def destroy
    user = Relationship.find(params[:id]).follower
    current_user.unfollow(user)
    @url = request.referer
    redirect_to @url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
    @book = Book.new
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following_user
    render :following
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.follower_user
    render :followers
  end

  def index
    @book = Book.new
    @user = current_user
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end
  
  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
      flash[:notice] = "successfully"
  	  redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<h4>Title</h4>
<h4>Opinion</h4>

  <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this obj from being saved
      <%= @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>  
  	<h4>Title</h4>
  	<%= f.text_field :title %>
  	<h4>Opinion</h4>
  	<%= f.text_area :body %>

    <%= f.submit 'Update Book' %>
  <% end %>

  <%= link_to "Show",  book_path %>|<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<div class="container">
  <% if @book.errors.any? %>
    <%= @book.errors.count %>error prohibited this obj from being saved
    <%= @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %> 

  <div class="row">

    <div class="col-xs-3">
      <h1>User info</h1>

      <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tr>
          <td><h4>name</h4></td>
          <td><%= @user.name %></td>
          </td>
        </tr>
        <tr>
          <td><h4>introduction</h4></td>
          <td><%= @user.introduction %></td>
        <tr>
          <td><h4>follow</h4></td>
          <td><%= link_to @user.following.count, following_user_path(@user) %></td>
        </tr>
        <tr>
          <td><h4>follower</h4></td>
          <td><%= link_to @user.follower.count, followers_user_path(@user) %></td>
        </tr>
      </table>

      <h1>New book</h1>
      <%= form_for(@book) do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <p><%= f.submit 'Create Book' %></p>
      <% end %>
    </div>

    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", size:'30x30' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>

            <% if book.favorited_by?(current_user) %>
              <td>       
                <%= link_to book_favorites_path(book,book.id), method: :delete do %>
                  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                  <%= book.favorites.count %>
                <% end %>
              </td>       
            <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                   <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                   <%= book.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td>
              コメント数:<%= book.comments.count %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>

  </div>

</div>

app/views/books/show.html.erb
<div class="container">
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>

  <div class="row">
    <div class="col-xs-3">

      <h1>User info</h1>
      <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tr>
          <td><h4>name</h4></td>
          <td><%= @book.user.name %></td>
          </td>
        </tr>
        <tr>
          <td><h4>introduction</h4></td>
          <td><%= @book.user.introduction %></td>
        <tr>
          <td><h4>follow</h4></td>
          <td><%= link_to @book.user.following.count, following_user_path(@book.user) %></td>
        </tr>
        <tr>
          <td><h4>follower</h4></td>
          <td><%= link_to @book.user.follower.count, followers_user_path(@book.user) %></td>
        </tr>
      </table>

      <% unless current_user == @book.user %>
        <% if current_user.following?(@book.user) %>
          <%= form_for(current_user.following.find_by(follower_id: @book.user.id), html: { method: :delete }) do |f| %>
            <%= hidden_field_tag :follower_id, @book.user.id %>
            <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
          <% end %>
        <% else %>
          <%= form_for(current_user.following.build) do |f| %>
            <%= hidden_field_tag :follower_id, @book.user.id %>
            <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
          <% end %>
        <% end %>
      <% end %>



      <h1>New book</h1>
      <%= form_for(@books) do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <p><%= f.submit 'Create Book' %></p>
      <% end %>

    </div>


    <div class="col-xs-9">
      <h1>Book detail</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tr>
          <td><%= attachment_image_tag @book.user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'30x30' %></td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>


          <% if @book.favorited_by?(current_user) %>
            <td>       
              <%= link_to book_favorites_path(@book), method: :delete do %>
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                <%= @book.favorites.count %>
              <% end %>
            </td>       
          <% else %>
            <td>
              <%= link_to book_favorites_path(@book), method: :post do %>
                 <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                 <%= @book.favorites.count %>
              <% end %>
            </td>
          <% end %>

          <td>コメント数:<%= @book.comments.count %></td>


          <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: '削除しますか？' }%></td>
          <% end %>
        </tr>        
      </table>
      <button type="button" class="btn btn-default btn-xs books-user-btn"><%= link_to @book.user.name, user_path(@book.user.id) %></button>
      
        <% if @comments.errors.any? %>
          <%= @comments.errors.count %>error prohibited this obj from being saved
          <%= @comments.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %> 



      <% @book.comments.each do |comments| %>
      <div class="row">
        <div class="col-xs-9">
          <div class="comment-index-box"><%= comments.comment %></div>
        </div>
        <div class="col-xs-2">
          <div><%= comments.user.name %></div>
        </div>

        <div class="col-xs-1">
          <% if comments.user == current_user %>
          <%= link_to "Destroy", book_comments_path(@book.id),  method: :delete %>
          <% end %>
        </div>


      </div>
      <% end %>







      <div class="row">
        <%= form_for [@book, @comment] do |f| %>
          <div class="col-xs-12 comment-box">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
          </div>
          <%= f.submit "送信する", class: "btn btn-success right comment-submit-btn" %>
        <% end %>
      </div>

  </div>
</div>

app/views/homes/index.html.erb
<div class="container">
  <h1>welcome to <span class="glyphicon glyphicon-book"></span>Bookers !!</h1>
</div>

app/views/homes/top.html.erb
<div class="container">

	<% if flash[:notice] %>
	  <p><%= flash[:notice] %></p>
	<% end %>


	<h1>welcome to <span class="glyphicon glyphicon-book"></span>Bookers !!</h1>

	<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
	<p>you can share and exchange your opinions , inpressions ,and eotions</p>
	<p>about various books!</p>
  <div class="row text-center">
    <%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-6 col-xs-offset-3" %>
  </div>
  <div class="row">
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-6 col-xs-offset-3" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersLevel2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="lead text-muted">Bookers</span>
        </nav>
        <nav class="nav navbar-nav navbar-right">
          <% if user_signed_in? %> 
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %></li>
              <li><%= link_to " logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out logout", method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to " Home", root_path, class: "glyphicon glyphicon-home" %></li>
              <li><%= link_to " About", home_about_path, class: "glyphicon glyphicon-link about"  %></li>
              <li><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
              <li><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in"  %></li>
            </ul>
          <% end %>
        </nav>
      </div>
    </header>



    <%= yield %>
  </body>     
</html>

app/views/users/edit.html.erb
<h1>User info</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <%= @user.errors.count %>error prohibited this obj from being saved
    <%= @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>  
  <h4>Name</h4>
  <%= f.text_field :name %>
  <h4>Image</h4>
  <%= f.attachment_field :profile_image %>
  <h4>Introduction</h4>
  <%= f.text_area :introduction %>
  <%= f.submit 'Update User' %>
<% end %>

app/views/users/followers.erb
<h1>Follower Users</h1>
<% provide(:title, @title) %>
<% @users.each do |user| %>



<table class="table">
  <thead>
  <tr>
     <th></th>
     <th>name</th>
     <th></th>
     <th></th>
     <th></th>
     <th></th>
  </tr>
</thead>

	
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'30x30' %></td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.following.count %></td>
      <td>フォロワー数:<%= user.follower.count %></td>

      <% unless current_user == user %>
        <% if current_user.following?(user) %>
          <td>
            <%= form_for(current_user.following.find_by(follower_id: user.id), html: { method: :delete }) do |f| %>
            <%= hidden_field_tag :follower_id, user.id %>
            <%= f.submit 'フォローを外す', class: 'btn btn-danger' %>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= form_for(current_user.following.build) do |f| %>
            <%= hidden_field_tag :follower_id, user.id %>
            <%= f.submit 'フォローする', class: 'btn btn-primary' %>
            <% end %>
          </td>
        <% end %>
      <% end %>



      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>

  <% end %>

</table>

app/views/users/following.erb
<h1>Follow Users</h1>
<% provide(:title, @title) %>
<% @users.each do |user| %>

<table class="table">
  <thead>
  <tr>
     <th></th>
     <th>name</th>
     <th></th>
     <th></th>
     <th></th>
     <th></th>
  </tr>
</thead>

	
    <tr>
      <td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'30x30' %></td>
      <td><%= user.name %></td>
      <td>フォロー数:<%= user.following.count %></td>
      <td>フォロワー数:<%= user.follower.count %></td>

      <% unless current_user == user %>
        <% if current_user.following?(user) %>
          <td>
            <%= form_for(current_user.following.find_by(follower_id: user.id), html: { method: :delete }) do |f| %>
            <%= hidden_field_tag :follower_id, user.id %>
            <%= f.submit 'フォローを外す', class: 'btn btn-danger' %>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= form_for(current_user.following.build) do |f| %>
            <%= hidden_field_tag :follower_id, user.id %>
            <%= f.submit 'フォローする', class: 'btn btn-primary' %>
            <% end %>
          </td>
        <% end %>
      <% end %>
      <td><%= link_to "Show", user_path(user.id) %></td>
    </tr>

</table>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">


    <div class="col-xs-3">
      <h1>User info</h1>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tr>
          <td><h4>name</h4></td>
          <td><%= @user.name %></td>
          </td>
        </tr>
        <tr>
          <td><h4>introduction</h4></td>
          <td><%= @user.introduction %></td>
        <tr>
          <td><h4>follow</h4></td>
          <td><%= link_to @user.following.count, following_user_path(@user) %></td>
        </tr>
        <tr>
          <td><h4>follower</h4></td>
          <td><%= link_to @user.follower.count, followers_user_path(@user) %></td>
        </tr>
      </table>
      




      <h1>New book</h1>
      <%= form_for(@book) do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <p><%= f.submit 'Create Book' %></p>
      <% end %>
    </div>


    <div class="col-xs-9">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
          	<th>image</th>
          	<th>name</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @users.each do |user| %>
        <tr>
        	<td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", size:'30x30' %></td>
        	<td><%= user.name %></td>
          <td>フォロー数:<%= @user.following.count %></td>
          <td>フォロワー数:<%= @user.follower.count %></td>

          <% unless current_user == user %>
            <% if current_user.following?(user) %>
            <td><%= form_for(current_user.following.find_by(follower_id: user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follower_id, user.id %>
              <%= f.submit 'フォローを外す', class: 'btn btn-danger' %>
            </td>
            <% end %>
            <% else %>
            <td><%= form_for(current_user.following.build) do |f| %>
              <%= hidden_field_tag :follower_id, user.id %>
              <%= f.submit 'フォローする', class: 'btn btn-primary' %>
            </td>
            <% end %>
            <% end %>
          <% else %>
            <td></td>
          <% end %>





        	<td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>



    

app/views/users/show.html.erb
<div class="container">
  <% if flash[:notice] %>
    <p><%= flash[:notice] %></p>
  <% end %>
  
  <div class="row">

    <div class="col-xs-3">
      <h1>User info</h1>
      <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tr>
          <td><h4>name</h4></td>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <td><h4>introduction</h4></td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr>
          <td><h4>follow</h4></td>
          <td><%= link_to @user.following.count, following_user_path(@user) %></td>
        </tr>
        <tr>
          <td><h4>follower</h4></td>
          <td><%= link_to @user.follower.count, followers_user_path(@user) %></td>
        </tr>
      </table>
  


      <% unless current_user == @user %>
        <% if current_user.following?(@user) %>
          <%= form_for(current_user.following.find_by(follower_id: @user.id), html: { method: :delete }) do |f| %>
            <%= hidden_field_tag :follower_id, @user.id %>
            <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
          <% end %>
        <% else %>
          <%= form_for(current_user.following.build) do |f| %>
            <%= hidden_field_tag :follower_id, @user.id %>
            <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
          <% end %>
        <% end %>
      <% end %>

      <% if @user.id == current_user.id %>
        <p><%= link_to "edit", edit_user_path(current_user.id) %></p>
      <% else %>
        <p><%= link_to "edit", user_path(current_user.id) %></p>
      <% end %>

      <h1>New book</h1>
      <%= form_for(@book) do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <p><%= f.submit 'Create Book' %></p>
      <% end %>
    </div>

    <div class="col-xs-9">
      <h1>Books</h1>

      <table class="table">
        <thead>
          <tr>
            <th></th>
          	<th>Title</th>
          	<th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <% @user.books.each do |book| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg",size:'30x30' %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>コメント数:<%= book.comments.count %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>